// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Desk32

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_LoadingScreen_screen_init();
    ui_HomeScreen_screen_init();
    ui_PomodoroScreen_screen_init();
    ui_TaskListScreen_screen_init();
    ui_CalendarScreen_screen_init();
    ui_SettingScreen_screen_init();
    ui_AboutScreen_screen_init();
    ui_HydrateScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_LoadingScreen);
}

void ui_destroy(void)
{
    ui_LoadingScreen_screen_destroy();
    ui_HomeScreen_screen_destroy();
    ui_PomodoroScreen_screen_destroy();
    ui_TaskListScreen_screen_destroy();
    ui_CalendarScreen_screen_destroy();
    ui_SettingScreen_screen_destroy();
    ui_AboutScreen_screen_destroy();
    ui_HydrateScreen_screen_destroy();
}
