// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Desk32

#ifndef _DESK32_UI_H
#define _DESK32_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_LoadingScreen.h"
#include "ui_HomeScreen.h"
#include "ui_PomodoroScreen.h"
#include "ui_TaskListScreen.h"
#include "ui_CalendarScreen.h"
#include "ui_SettingScreen.h"
#include "ui_AboutScreen.h"
#include "ui_HydrateScreen.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_desk32_png);    // assets/Desk32.png
LV_IMG_DECLARE(ui_img_tempicon_png);    // assets/TempIcon.png
LV_IMG_DECLARE(ui_img_humidityicon_png);    // assets/HumidityIcon.png
LV_IMG_DECLARE(ui_img_brightnessicon_png);    // assets/BrightnessIcon.png
LV_IMG_DECLARE(ui_img_about_png);    // assets/About.png
LV_IMG_DECLARE(ui_img_watericon_png);    // assets/WaterIcon.png

// FONTS
LV_FONT_DECLARE(ui_font_OswaldLight20);
LV_FONT_DECLARE(ui_font_OswaldLight24);
LV_FONT_DECLARE(ui_font_OswaldLight32);
LV_FONT_DECLARE(ui_font_OswaldMedium20);
LV_FONT_DECLARE(ui_font_OswaldMedium32);
LV_FONT_DECLARE(ui_font_OswaldMedium48);
LV_FONT_DECLARE(ui_font_OswaldMedium80);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
