// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Desk32

#ifndef UI_ABOUTSCREEN_H
#define UI_ABOUTSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_AboutScreen
extern void ui_AboutScreen_screen_init(void);
extern void ui_AboutScreen_screen_destroy(void);
extern void ui_event_AboutScreen(lv_event_t * e);
extern lv_obj_t * ui_AboutScreen;
extern lv_obj_t * ui_Image2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

