// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Desk32

#ifndef UI_CALENDARSCREEN_H
#define UI_CALENDARSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_CalendarScreen
extern void ui_CalendarScreen_screen_init(void);
extern void ui_CalendarScreen_screen_destroy(void);
extern void ui_event_CalendarScreen(lv_event_t * e);
extern lv_obj_t * ui_CalendarScreen;
extern lv_obj_t * ui_Calendar1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

