// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Desk32

#include "ui.h"

lv_obj_t * ui_CalendarScreen = NULL;
lv_obj_t * ui_Calendar1 = NULL;
// event funtions
void ui_event_CalendarScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SettingScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_SettingScreen_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_TaskListScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_TaskListScreen_screen_init);
    }
}

// build funtions

void ui_CalendarScreen_screen_init(void)
{
    ui_CalendarScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_CalendarScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CalendarScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CalendarScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Calendar1 = lv_calendar_create(ui_CalendarScreen);
    lv_calendar_set_today_date(ui_Calendar1, 2026, 1, 1);
    lv_calendar_set_showed_date(ui_Calendar1, 2026, 1);
    lv_obj_t * ui_Calendar1_header = lv_calendar_header_arrow_create(ui_Calendar1);
    lv_obj_set_width(ui_Calendar1, lv_pct(95));
    lv_obj_set_height(ui_Calendar1, lv_pct(95));
    lv_obj_set_align(ui_Calendar1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Calendar1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Calendar1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Calendar1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_CalendarScreen, ui_event_CalendarScreen, LV_EVENT_ALL, NULL);

}

void ui_CalendarScreen_screen_destroy(void)
{
    if(ui_CalendarScreen) lv_obj_del(ui_CalendarScreen);

    // NULL screen variables
    ui_CalendarScreen = NULL;
    ui_Calendar1 = NULL;

}
