// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Desk32

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void startPomodoro(lv_event_t * e);
void stopPomodoro(lv_event_t * e);
void onUpdateWeatherClick(lv_event_t * e);
void onSyncTimeClick(lv_event_t * e);
void onWaterSwitchToggle(lv_event_t * e);
void onBrightnessChange(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
