// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Desk32

#include "ui.h"

lv_obj_t * ui_HydrateScreen = NULL;
lv_obj_t * ui_ButtonClose = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Image3 = NULL;
// event funtions
void ui_event_ButtonClose(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_HomeScreen_screen_init);
    }
}

// build funtions

void ui_HydrateScreen_screen_init(void)
{
    ui_HydrateScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HydrateScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HydrateScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HydrateScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonClose = lv_btn_create(ui_HydrateScreen);
    lv_obj_set_width(ui_ButtonClose, 50);
    lv_obj_set_height(ui_ButtonClose, 50);
    lv_obj_set_x(ui_ButtonClose, lv_pct(41));
    lv_obj_set_y(ui_ButtonClose, lv_pct(-38));
    lv_obj_set_align(ui_ButtonClose, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonClose, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonClose, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonClose, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonClose, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonClose, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_ButtonClose);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "X");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_HydrateScreen);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 70);
    lv_obj_set_y(ui_Label3, lv_pct(20));
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Hydrate \nYourself");
    lv_obj_set_style_text_font(ui_Label3, &ui_font_OswaldMedium48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_img_create(ui_HydrateScreen);
    lv_img_set_src(ui_Image3, &ui_img_watericon_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image3, -80);
    lv_obj_set_y(ui_Image3, 46);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_ButtonClose, ui_event_ButtonClose, LV_EVENT_ALL, NULL);

}

void ui_HydrateScreen_screen_destroy(void)
{
    if(ui_HydrateScreen) lv_obj_del(ui_HydrateScreen);

    // NULL screen variables
    ui_HydrateScreen = NULL;
    ui_ButtonClose = NULL;
    ui_Label2 = NULL;
    ui_Label3 = NULL;
    ui_Image3 = NULL;

}
