// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Desk32

#ifndef UI_HOMESCREEN_H
#define UI_HOMESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_HomeScreen
extern void ui_HomeScreen_screen_init(void);
extern void ui_HomeScreen_screen_destroy(void);
extern void ui_event_HomeScreen(lv_event_t * e);
extern lv_obj_t * ui_HomeScreen;
extern lv_obj_t * ui_ContainerTime;
extern lv_obj_t * ui_LabelAMPM;
extern lv_obj_t * ui_LabelTime;
extern lv_obj_t * ui_ContainerDate;
extern lv_obj_t * ui_LabelDate;
extern lv_obj_t * ui_LabelDay;
extern lv_obj_t * ui_ContainerTemp;
extern lv_obj_t * ui_LabelTemp;
extern lv_obj_t * ui_LabelHum;
extern lv_obj_t * ui_ImageTempIcon;
extern lv_obj_t * ui_ImageHumIcon;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

