// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Desk32

#ifndef UI_HYDRATESCREEN_H
#define UI_HYDRATESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_HydrateScreen
extern void ui_HydrateScreen_screen_init(void);
extern void ui_HydrateScreen_screen_destroy(void);
extern lv_obj_t * ui_HydrateScreen;
extern void ui_event_ButtonClose(lv_event_t * e);
extern lv_obj_t * ui_ButtonClose;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Image3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

