// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Desk32

#include "ui.h"

lv_obj_t * ui_HomeScreen = NULL;
lv_obj_t * ui_ContainerTime = NULL;
lv_obj_t * ui_LabelAMPM = NULL;
lv_obj_t * ui_LabelTime = NULL;
lv_obj_t * ui_ContainerDate = NULL;
lv_obj_t * ui_LabelDate = NULL;
lv_obj_t * ui_LabelDay = NULL;
lv_obj_t * ui_ContainerTemp = NULL;
lv_obj_t * ui_LabelTemp = NULL;
lv_obj_t * ui_LabelHum = NULL;
lv_obj_t * ui_ImageTempIcon = NULL;
lv_obj_t * ui_ImageHumIcon = NULL;
// event funtions
void ui_event_HomeScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_PomodoroScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_PomodoroScreen_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_AboutScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_AboutScreen_screen_init);
    }
}

// build funtions

void ui_HomeScreen_screen_init(void)
{
    ui_HomeScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HomeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HomeScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerTime = lv_obj_create(ui_HomeScreen);
    lv_obj_remove_style_all(ui_ContainerTime);
    lv_obj_set_height(ui_ContainerTime, 75);
    lv_obj_set_width(ui_ContainerTime, lv_pct(100));
    lv_obj_set_x(ui_ContainerTime, 0);
    lv_obj_set_y(ui_ContainerTime, lv_pct(-18));
    lv_obj_set_align(ui_ContainerTime, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerTime, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelAMPM = lv_label_create(ui_ContainerTime);
    lv_obj_set_width(ui_LabelAMPM, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAMPM, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelAMPM, lv_pct(33));
    lv_obj_set_y(ui_LabelAMPM, lv_pct(23));
    lv_obj_set_align(ui_LabelAMPM, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelAMPM, "--");
    lv_obj_set_style_text_font(ui_LabelAMPM, &ui_font_OswaldLight32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTime = lv_label_create(ui_ContainerTime);
    lv_obj_set_width(ui_LabelTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTime, lv_pct(-5));
    lv_obj_set_y(ui_LabelTime, lv_pct(5));
    lv_obj_set_align(ui_LabelTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTime, "--:--");
    lv_obj_set_style_text_font(ui_LabelTime, &ui_font_OswaldMedium80, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerDate = lv_obj_create(ui_HomeScreen);
    lv_obj_remove_style_all(ui_ContainerDate);
    lv_obj_set_height(ui_ContainerDate, 40);
    lv_obj_set_width(ui_ContainerDate, lv_pct(100));
    lv_obj_set_x(ui_ContainerDate, 0);
    lv_obj_set_y(ui_ContainerDate, lv_pct(15));
    lv_obj_set_align(ui_ContainerDate, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerDate, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelDate = lv_label_create(ui_ContainerDate);
    lv_obj_set_width(ui_LabelDate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDate, lv_pct(15));
    lv_obj_set_y(ui_LabelDate, lv_pct(0));
    lv_obj_set_align(ui_LabelDate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDate, "-- --- ----");
    lv_obj_set_style_text_font(ui_LabelDate, &ui_font_OswaldLight24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDay = lv_label_create(ui_ContainerDate);
    lv_obj_set_width(ui_LabelDay, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDay, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDay, lv_pct(-20));
    lv_obj_set_y(ui_LabelDay, lv_pct(0));
    lv_obj_set_align(ui_LabelDay, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDay, "---");
    lv_obj_set_style_text_font(ui_LabelDay, &ui_font_OswaldLight24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerTemp = lv_obj_create(ui_HomeScreen);
    lv_obj_remove_style_all(ui_ContainerTemp);
    lv_obj_set_height(ui_ContainerTemp, 40);
    lv_obj_set_width(ui_ContainerTemp, lv_pct(100));
    lv_obj_set_x(ui_ContainerTemp, 0);
    lv_obj_set_y(ui_ContainerTemp, lv_pct(32));
    lv_obj_set_align(ui_ContainerTemp, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerTemp, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelTemp = lv_label_create(ui_ContainerTemp);
    lv_obj_set_width(ui_LabelTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTemp, lv_pct(-12));
    lv_obj_set_y(ui_LabelTemp, lv_pct(0));
    lv_obj_set_align(ui_LabelTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTemp, "-- °C");
    lv_obj_set_style_text_font(ui_LabelTemp, &ui_font_OswaldLight24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHum = lv_label_create(ui_ContainerTemp);
    lv_obj_set_width(ui_LabelHum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHum, lv_pct(22));
    lv_obj_set_y(ui_LabelHum, lv_pct(0));
    lv_obj_set_align(ui_LabelHum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHum, "-- %");
    lv_obj_set_style_text_font(ui_LabelHum, &ui_font_OswaldLight24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageTempIcon = lv_img_create(ui_ContainerTemp);
    lv_img_set_src(ui_ImageTempIcon, &ui_img_tempicon_png);
    lv_obj_set_width(ui_ImageTempIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageTempIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageTempIcon, -85);
    lv_obj_set_y(ui_ImageTempIcon, 0);
    lv_obj_set_align(ui_ImageTempIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageTempIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageTempIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageHumIcon = lv_img_create(ui_ContainerTemp);
    lv_img_set_src(ui_ImageHumIcon, &ui_img_humidityicon_png);
    lv_obj_set_width(ui_ImageHumIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageHumIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageHumIcon, 30);
    lv_obj_set_y(ui_ImageHumIcon, 0);
    lv_obj_set_align(ui_ImageHumIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageHumIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageHumIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_HomeScreen, ui_event_HomeScreen, LV_EVENT_ALL, NULL);

}

void ui_HomeScreen_screen_destroy(void)
{
    if(ui_HomeScreen) lv_obj_del(ui_HomeScreen);

    // NULL screen variables
    ui_HomeScreen = NULL;
    ui_ContainerTime = NULL;
    ui_LabelAMPM = NULL;
    ui_LabelTime = NULL;
    ui_ContainerDate = NULL;
    ui_LabelDate = NULL;
    ui_LabelDay = NULL;
    ui_ContainerTemp = NULL;
    ui_LabelTemp = NULL;
    ui_LabelHum = NULL;
    ui_ImageTempIcon = NULL;
    ui_ImageHumIcon = NULL;

}
