// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Desk32

#ifndef UI_LOADINGSCREEN_H
#define UI_LOADINGSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_LoadingScreen
extern void ui_LoadingScreen_screen_init(void);
extern void ui_LoadingScreen_screen_destroy(void);
extern void ui_event_LoadingScreen(lv_event_t * e);
extern lv_obj_t * ui_LoadingScreen;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Spinner1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

