// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Desk32

#ifndef UI_POMODOROSCREEN_H
#define UI_POMODOROSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_PomodoroScreen
extern void ui_PomodoroScreen_screen_init(void);
extern void ui_PomodoroScreen_screen_destroy(void);
extern void ui_event_PomodoroScreen(lv_event_t * e);
extern lv_obj_t * ui_PomodoroScreen;
extern lv_obj_t * ui_ArcPomo;
extern lv_obj_t * ui_LabelPomoTime;
extern void ui_event_ButtonStart(lv_event_t * e);
extern lv_obj_t * ui_ButtonStart;
extern lv_obj_t * ui_LabelStart;
extern void ui_event_ButtonReset(lv_event_t * e);
extern lv_obj_t * ui_ButtonReset;
extern lv_obj_t * ui_LabelReset;
extern lv_obj_t * ui_LabelPomoStatus;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

