// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Desk32

#include "ui.h"

lv_obj_t * ui_PomodoroScreen = NULL;
lv_obj_t * ui_ArcPomo = NULL;
lv_obj_t * ui_LabelPomoTime = NULL;
lv_obj_t * ui_ButtonStart = NULL;
lv_obj_t * ui_LabelStart = NULL;
lv_obj_t * ui_ButtonReset = NULL;
lv_obj_t * ui_LabelReset = NULL;
lv_obj_t * ui_LabelPomoStatus = NULL;
// event funtions
void ui_event_PomodoroScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_TaskListScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_TaskListScreen_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_HomeScreen_screen_init);
    }
}

void ui_event_ButtonStart(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        startPomodoro(e);
    }
}

void ui_event_ButtonReset(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        stopPomodoro(e);
    }
}

// build funtions

void ui_PomodoroScreen_screen_init(void)
{
    ui_PomodoroScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PomodoroScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PomodoroScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PomodoroScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcPomo = lv_arc_create(ui_PomodoroScreen);
    lv_obj_set_width(ui_ArcPomo, 220);
    lv_obj_set_height(ui_ArcPomo, 220);
    lv_obj_set_x(ui_ArcPomo, 0);
    lv_obj_set_y(ui_ArcPomo, 5);
    lv_obj_set_align(ui_ArcPomo, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ArcPomo, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_ArcPomo, 100);
    lv_arc_set_bg_angles(ui_ArcPomo, 150, 30);

    lv_obj_set_style_arc_color(ui_ArcPomo, lv_color_hex(0x626062), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcPomo, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcPomo, lv_color_hex(0x349EF9), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcPomo, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ArcPomo, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelPomoTime = lv_label_create(ui_PomodoroScreen);
    lv_obj_set_width(ui_LabelPomoTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPomoTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPomoTime, 0);
    lv_obj_set_y(ui_LabelPomoTime, -25);
    lv_obj_set_align(ui_LabelPomoTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPomoTime, "25:00");
    lv_obj_set_style_text_font(ui_LabelPomoTime, &ui_font_OswaldMedium48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonStart = lv_btn_create(ui_PomodoroScreen);
    lv_obj_set_width(ui_ButtonStart, 65);
    lv_obj_set_height(ui_ButtonStart, 40);
    lv_obj_set_x(ui_ButtonStart, -40);
    lv_obj_set_y(ui_ButtonStart, 75);
    lv_obj_set_align(ui_ButtonStart, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonStart, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonStart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonStart, lv_color_hex(0x2DA041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonStart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelStart = lv_label_create(ui_ButtonStart);
    lv_obj_set_width(ui_LabelStart, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelStart, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelStart, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelStart, "START");
    lv_obj_set_style_text_font(ui_LabelStart, &ui_font_OswaldLight20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonReset = lv_btn_create(ui_PomodoroScreen);
    lv_obj_set_width(ui_ButtonReset, 65);
    lv_obj_set_height(ui_ButtonReset, 40);
    lv_obj_set_x(ui_ButtonReset, 40);
    lv_obj_set_y(ui_ButtonReset, 75);
    lv_obj_set_align(ui_ButtonReset, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonReset, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonReset, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonReset, lv_color_hex(0x2DA041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonReset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelReset = lv_label_create(ui_ButtonReset);
    lv_obj_set_width(ui_LabelReset, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelReset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelReset, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelReset, "X");
    lv_obj_set_style_text_font(ui_LabelReset, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPomoStatus = lv_label_create(ui_PomodoroScreen);
    lv_obj_set_width(ui_LabelPomoStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPomoStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPomoStatus, 0);
    lv_obj_set_y(ui_LabelPomoStatus, 25);
    lv_obj_set_align(ui_LabelPomoStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPomoStatus, "Focus Mode");
    lv_obj_set_style_text_font(ui_LabelPomoStatus, &ui_font_OswaldLight24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonStart, ui_event_ButtonStart, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonReset, ui_event_ButtonReset, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PomodoroScreen, ui_event_PomodoroScreen, LV_EVENT_ALL, NULL);

}

void ui_PomodoroScreen_screen_destroy(void)
{
    if(ui_PomodoroScreen) lv_obj_del(ui_PomodoroScreen);

    // NULL screen variables
    ui_PomodoroScreen = NULL;
    ui_ArcPomo = NULL;
    ui_LabelPomoTime = NULL;
    ui_ButtonStart = NULL;
    ui_LabelStart = NULL;
    ui_ButtonReset = NULL;
    ui_LabelReset = NULL;
    ui_LabelPomoStatus = NULL;

}
