// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Desk32

#include "ui.h"

lv_obj_t * ui_SettingScreen = NULL;
lv_obj_t * ui_LabelSettingsTitle = NULL;
lv_obj_t * ui_PanelWifi = NULL;
lv_obj_t * ui_LabelWifiSSID = NULL;
lv_obj_t * ui_LabelWifiStatus = NULL;
lv_obj_t * ui_PanelControls = NULL;
lv_obj_t * ui_BtnRefTemp = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_BtnSyncTime = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_PanelHealth = NULL;
lv_obj_t * ui_LabelWater = NULL;
lv_obj_t * ui_SwitchWater = NULL;
lv_obj_t * ui_PanelHBrightness = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_SliderBrightness = NULL;
lv_obj_t * ui_LabelMin = NULL;
lv_obj_t * ui_LabelMax = NULL;
lv_obj_t * ui_PanelSpacer = NULL;
// event funtions
void ui_event_SettingScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_CalendarScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_CalendarScreen_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_AboutScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_AboutScreen_screen_init);
    }
}

void ui_event_BtnRefTemp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        onUpdateWeatherClick(e);
    }
}

void ui_event_BtnSyncTime(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        onSyncTimeClick(e);
    }
}

void ui_event_SwitchWater(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        onWaterSwitchToggle(e);
    }
}

void ui_event_SliderBrightness(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        onBrightnessChange(e);
    }
}

// build funtions

void ui_SettingScreen_screen_init(void)
{
    ui_SettingScreen = lv_obj_create(NULL);
    lv_obj_add_flag(ui_SettingScreen, LV_OBJ_FLAG_SCROLL_WITH_ARROW);     /// Flags
    lv_obj_set_style_bg_color(ui_SettingScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSettingsTitle = lv_label_create(ui_SettingScreen);
    lv_obj_set_width(ui_LabelSettingsTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSettingsTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSettingsTitle, -42);
    lv_obj_set_y(ui_LabelSettingsTitle, -95);
    lv_obj_set_align(ui_LabelSettingsTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSettingsTitle, "DEVICE SETTINGS");
    lv_obj_set_style_text_font(ui_LabelSettingsTitle, &ui_font_OswaldMedium32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelWifi = lv_obj_create(ui_SettingScreen);
    lv_obj_set_height(ui_PanelWifi, 60);
    lv_obj_set_width(ui_PanelWifi, lv_pct(94));
    lv_obj_set_x(ui_PanelWifi, -3);
    lv_obj_set_y(ui_PanelWifi, -45);
    lv_obj_set_align(ui_PanelWifi, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelWifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelWifi, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelWifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelWifi, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelWifiSSID = lv_label_create(ui_PanelWifi);
    lv_obj_set_width(ui_LabelWifiSSID, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWifiSSID, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelWifiSSID, 0);
    lv_obj_set_y(ui_LabelWifiSSID, -15);
    lv_obj_set_align(ui_LabelWifiSSID, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelWifiSSID, "SSID: --");
    lv_obj_set_style_text_font(ui_LabelWifiSSID, &ui_font_OswaldMedium20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelWifiStatus = lv_label_create(ui_PanelWifi);
    lv_obj_set_width(ui_LabelWifiStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWifiStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelWifiStatus, 0);
    lv_obj_set_y(ui_LabelWifiStatus, 12);
    lv_obj_set_align(ui_LabelWifiStatus, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelWifiStatus, "Status: --");
    lv_obj_set_style_text_font(ui_LabelWifiStatus, &ui_font_OswaldMedium20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelControls = lv_obj_create(ui_SettingScreen);
    lv_obj_set_height(ui_PanelControls, 50);
    lv_obj_set_width(ui_PanelControls, lv_pct(94));
    lv_obj_set_x(ui_PanelControls, -3);
    lv_obj_set_y(ui_PanelControls, 15);
    lv_obj_set_align(ui_PanelControls, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelControls, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelControls, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelControls, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelControls, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnRefTemp = lv_btn_create(ui_PanelControls);
    lv_obj_set_width(ui_BtnRefTemp, 180);
    lv_obj_set_height(ui_BtnRefTemp, 30);
    lv_obj_set_x(ui_BtnRefTemp, -7);
    lv_obj_set_y(ui_BtnRefTemp, 0);
    lv_obj_set_align(ui_BtnRefTemp, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_BtnRefTemp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnRefTemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_BtnRefTemp);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Refresh Temperature");
    lv_obj_set_style_text_align(ui_Label4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &ui_font_OswaldMedium20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnSyncTime = lv_btn_create(ui_PanelControls);
    lv_obj_set_width(ui_BtnSyncTime, 100);
    lv_obj_set_height(ui_BtnSyncTime, 30);
    lv_obj_set_x(ui_BtnSyncTime, 7);
    lv_obj_set_y(ui_BtnSyncTime, 0);
    lv_obj_set_align(ui_BtnSyncTime, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_BtnSyncTime, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnSyncTime, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_BtnSyncTime);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Sync Time");
    lv_obj_set_style_text_font(ui_Label5, &ui_font_OswaldMedium20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelHealth = lv_obj_create(ui_SettingScreen);
    lv_obj_set_height(ui_PanelHealth, 50);
    lv_obj_set_width(ui_PanelHealth, lv_pct(94));
    lv_obj_set_x(ui_PanelHealth, -3);
    lv_obj_set_y(ui_PanelHealth, 70);
    lv_obj_set_align(ui_PanelHealth, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelHealth, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelHealth, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelHealth, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelHealth, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelWater = lv_label_create(ui_PanelHealth);
    lv_obj_set_width(ui_LabelWater, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWater, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelWater, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelWater, "Water Reminder");
    lv_obj_set_style_text_font(ui_LabelWater, &ui_font_OswaldMedium20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchWater = lv_switch_create(ui_PanelHealth);
    lv_obj_set_width(ui_SwitchWater, 50);
    lv_obj_set_height(ui_SwitchWater, 25);
    lv_obj_set_align(ui_SwitchWater, LV_ALIGN_RIGHT_MID);
    lv_obj_add_state(ui_SwitchWater, LV_STATE_CHECKED);       /// States

    ui_PanelHBrightness = lv_obj_create(ui_SettingScreen);
    lv_obj_set_height(ui_PanelHBrightness, 50);
    lv_obj_set_width(ui_PanelHBrightness, lv_pct(94));
    lv_obj_set_x(ui_PanelHBrightness, -3);
    lv_obj_set_y(ui_PanelHBrightness, 125);
    lv_obj_set_align(ui_PanelHBrightness, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelHBrightness, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelHBrightness, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelHBrightness, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelHBrightness, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_img_create(ui_PanelHBrightness);
    lv_img_set_src(ui_Image4, &ui_img_brightnessicon_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image4, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SliderBrightness = lv_slider_create(ui_PanelHBrightness);
    lv_slider_set_range(ui_SliderBrightness, 10, 100);
    lv_slider_set_value(ui_SliderBrightness, 100, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderBrightness) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderBrightness, 0,
                                                                                                     LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderBrightness, 150);
    lv_obj_set_height(ui_SliderBrightness, 10);
    lv_obj_set_x(ui_SliderBrightness, -35);
    lv_obj_set_y(ui_SliderBrightness, 0);
    lv_obj_set_align(ui_SliderBrightness, LV_ALIGN_RIGHT_MID);

    ui_LabelMin = lv_label_create(ui_PanelHBrightness);
    lv_obj_set_width(ui_LabelMin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMin, -70);
    lv_obj_set_y(ui_LabelMin, 0);
    lv_obj_set_align(ui_LabelMin, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMin, "10%");
    lv_obj_set_style_text_font(ui_LabelMin, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMax = lv_label_create(ui_PanelHBrightness);
    lv_obj_set_width(ui_LabelMax, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMax, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMax, 130);
    lv_obj_set_y(ui_LabelMax, 0);
    lv_obj_set_align(ui_LabelMax, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMax, "100%");
    lv_obj_set_style_text_font(ui_LabelMax, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSpacer = lv_obj_create(ui_SettingScreen);
    lv_obj_set_height(ui_PanelSpacer, 4);
    lv_obj_set_width(ui_PanelSpacer, lv_pct(94));
    lv_obj_set_x(ui_PanelSpacer, -3);
    lv_obj_set_y(ui_PanelSpacer, 155);
    lv_obj_set_align(ui_PanelSpacer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelSpacer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelSpacer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSpacer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSpacer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BtnRefTemp, ui_event_BtnRefTemp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnSyncTime, ui_event_BtnSyncTime, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwitchWater, ui_event_SwitchWater, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderBrightness, ui_event_SliderBrightness, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SettingScreen, ui_event_SettingScreen, LV_EVENT_ALL, NULL);

}

void ui_SettingScreen_screen_destroy(void)
{
    if(ui_SettingScreen) lv_obj_del(ui_SettingScreen);

    // NULL screen variables
    ui_SettingScreen = NULL;
    ui_LabelSettingsTitle = NULL;
    ui_PanelWifi = NULL;
    ui_LabelWifiSSID = NULL;
    ui_LabelWifiStatus = NULL;
    ui_PanelControls = NULL;
    ui_BtnRefTemp = NULL;
    ui_Label4 = NULL;
    ui_BtnSyncTime = NULL;
    ui_Label5 = NULL;
    ui_PanelHealth = NULL;
    ui_LabelWater = NULL;
    ui_SwitchWater = NULL;
    ui_PanelHBrightness = NULL;
    ui_Image4 = NULL;
    ui_SliderBrightness = NULL;
    ui_LabelMin = NULL;
    ui_LabelMax = NULL;
    ui_PanelSpacer = NULL;

}
