// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Desk32

#ifndef UI_SETTINGSCREEN_H
#define UI_SETTINGSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SettingScreen
extern void ui_SettingScreen_screen_init(void);
extern void ui_SettingScreen_screen_destroy(void);
extern void ui_event_SettingScreen(lv_event_t * e);
extern lv_obj_t * ui_SettingScreen;
extern lv_obj_t * ui_LabelSettingsTitle;
extern lv_obj_t * ui_PanelWifi;
extern lv_obj_t * ui_LabelWifiSSID;
extern lv_obj_t * ui_LabelWifiStatus;
extern lv_obj_t * ui_PanelControls;
extern void ui_event_BtnRefTemp(lv_event_t * e);
extern lv_obj_t * ui_BtnRefTemp;
extern lv_obj_t * ui_Label4;
extern void ui_event_BtnSyncTime(lv_event_t * e);
extern lv_obj_t * ui_BtnSyncTime;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_PanelHealth;
extern lv_obj_t * ui_LabelWater;
extern void ui_event_SwitchWater(lv_event_t * e);
extern lv_obj_t * ui_SwitchWater;
extern lv_obj_t * ui_PanelHBrightness;
extern lv_obj_t * ui_Image4;
extern void ui_event_SliderBrightness(lv_event_t * e);
extern lv_obj_t * ui_SliderBrightness;
extern lv_obj_t * ui_LabelMin;
extern lv_obj_t * ui_LabelMax;
extern lv_obj_t * ui_PanelSpacer;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

