// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Desk32

#ifndef UI_TASKLISTSCREEN_H
#define UI_TASKLISTSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_TaskListScreen
extern void ui_TaskListScreen_screen_init(void);
extern void ui_TaskListScreen_screen_destroy(void);
extern void ui_event_TaskListScreen(lv_event_t * e);
extern lv_obj_t * ui_TaskListScreen;
extern void ui_event_TextAreaTaskInput(lv_event_t * e);
extern lv_obj_t * ui_TextAreaTaskInput;
extern void ui_event_ContainerTaskList(lv_event_t * e);
extern lv_obj_t * ui_ContainerTaskList;
extern void ui_event_Keyboard1(lv_event_t * e);
extern lv_obj_t * ui_Keyboard1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

