// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Desk32

#include "ui.h"

lv_obj_t * ui_TaskListScreen = NULL;
lv_obj_t * ui_TextAreaTaskInput = NULL;
lv_obj_t * ui_ContainerTaskList = NULL;
lv_obj_t * ui_Keyboard1 = NULL;
// event funtions
void ui_event_TaskListScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_PomodoroScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_PomodoroScreen_screen_init);
    }
    if(event_code == LV_EVENT_RELEASED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_CalendarScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_CalendarScreen_screen_init);
    }
}

void ui_event_TextAreaTaskInput(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_ContainerTaskList(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Keyboard1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

// build funtions

void ui_TaskListScreen_screen_init(void)
{
    ui_TaskListScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_TaskListScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TaskListScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TaskListScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextAreaTaskInput = lv_textarea_create(ui_TaskListScreen);
    lv_obj_set_width(ui_TextAreaTaskInput, lv_pct(95));
    lv_obj_set_height(ui_TextAreaTaskInput, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_TextAreaTaskInput, 0);
    lv_obj_set_y(ui_TextAreaTaskInput, -90);
    lv_obj_set_align(ui_TextAreaTaskInput, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextAreaTaskInput, 25);
    lv_textarea_set_placeholder_text(ui_TextAreaTaskInput, "Enter a task here");
    lv_textarea_set_one_line(ui_TextAreaTaskInput, true);
    lv_obj_set_style_text_font(ui_TextAreaTaskInput, &ui_font_OswaldLight20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_TextAreaTaskInput, lv_color_hex(0x4C4D52), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextAreaTaskInput, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_ContainerTaskList = lv_obj_create(ui_TaskListScreen);
    lv_obj_set_height(ui_ContainerTaskList, 175);
    lv_obj_set_width(ui_ContainerTaskList, lv_pct(95));
    lv_obj_set_x(ui_ContainerTaskList, 0);
    lv_obj_set_y(ui_ContainerTaskList, 25);
    lv_obj_set_align(ui_ContainerTaskList, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContainerTaskList, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ContainerTaskList, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_scroll_dir(ui_ContainerTaskList, LV_DIR_VER);
    lv_obj_set_style_bg_color(ui_ContainerTaskList, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerTaskList, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ContainerTaskList, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard1 = lv_keyboard_create(ui_TaskListScreen);
    lv_obj_set_width(ui_Keyboard1, 320);
    lv_obj_set_height(ui_Keyboard1, 150);
    lv_obj_set_x(ui_Keyboard1, 0);
    lv_obj_set_y(ui_Keyboard1, 45);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_TextAreaTaskInput, ui_event_TextAreaTaskInput, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ContainerTaskList, ui_event_ContainerTaskList, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard1, ui_TextAreaTaskInput);
    lv_obj_add_event_cb(ui_Keyboard1, ui_event_Keyboard1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TaskListScreen, ui_event_TaskListScreen, LV_EVENT_ALL, NULL);

}

void ui_TaskListScreen_screen_destroy(void)
{
    if(ui_TaskListScreen) lv_obj_del(ui_TaskListScreen);

    // NULL screen variables
    ui_TaskListScreen = NULL;
    ui_TextAreaTaskInput = NULL;
    ui_ContainerTaskList = NULL;
    ui_Keyboard1 = NULL;

}
